// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package productdb

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       float64
	SKU         string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
