// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package productdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description, price, sku)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, sku, created_at, updated_at
`

type CreateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       float64
	SKU         string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.SKU,
	)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.Price, &i.SKU, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, sku, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.Price, &i.SKU, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, sku, created_at, updated_at
FROM products
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ID, &i.Name, &i.Description, &i.Price, &i.SKU, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) AS count FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name        = $2,
    description = $3,
    price       = $4,
    sku         = $5,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, description, price, sku, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       float64
	SKU         string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.SKU,
	)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.Price, &i.SKU, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const existsProductBySKU = `-- name: ExistsProductBySKU :one
SELECT EXISTS(SELECT 1 FROM products WHERE sku = $1) AS exists
`

func (q *Queries) ExistsProductBySKU(ctx context.Context, sku string) (bool, error) {
	row := q.db.QueryRow(ctx, existsProductBySKU, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
